const { executeQuery } = require('./connection');
const fs = require('fs');
const path = require('path');

async function initializeDatabase() {
  try {
    console.log('Initializing database...');
    
    // Check if users table exists
    const checkTableSql = `
      SELECT COUNT(*) as count
      FROM user_tables
      WHERE table_name = 'USERS'
    `;
    
    const result = await executeQuery(checkTableSql);
    const tableExists = result.rows && result.rows.length > 0 && result.rows[0].COUNT > 0;
    
    if (!tableExists) {
      console.log('Creating users table...');
      
      const createTableSql = `
        CREATE TABLE users (
          user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          username VARCHAR2(100) NOT NULL,
          email VARCHAR2(100) NOT NULL UNIQUE,
          password VARCHAR2(255) NOT NULL,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
      `;
      
      await executeQuery(createTableSql, {}, { autoCommit: true });
      console.log('Users table created successfully');
      
      // Create index on email
      const createIndexSql = `CREATE INDEX idx_users_email ON users(email)`;
      await executeQuery(createIndexSql, {}, { autoCommit: true });
      console.log('Email index created successfully');
    } else {
      console.log('Users table already exists');
    }
    
    console.log('Database initialization complete');
  } catch (error) {
    console.error('Error initializing database:', error);
    throw error;
  }
}

// Run if called directly
if (require.main === module) {
  const { initializePool, closePool } = require('./connection');
  
  initializePool()
    .then(() => initializeDatabase())
    .then(() => {
      console.log('Database initialized successfully');
      return closePool();
    })
    .then(() => process.exit(0))
    .catch(err => {
      console.error('Failed to initialize database:', err);
      process.exit(1);
    });
}

module.exports = { initializeDatabase };

