-- Create users table if it doesn't exist
BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE users (
       user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       username VARCHAR2(100) NOT NULL,
       email VARCHAR2(100) NOT NULL UNIQUE,
       password VARCHAR2(255) NOT NULL,
       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
   )';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE = -955 THEN
         NULL; -- Table already exists
      ELSE
         RAISE;
      END IF;
END;
/

-- Create index on email for faster lookups
BEGIN
   EXECUTE IMMEDIATE 'CREATE INDEX idx_users_email ON users(email)';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE = -955 THEN
         NULL; -- Index already exists
      ELSE
         RAISE;
      END IF;
END;
/

